/* Untyped file generated by genType. */

import * as CookieBoxBS from "./CookieBox.bs";

import * as ReasonReact from "reason-react/src/ReasonReact.js";

export const CookieBox = ReasonReact.wrapReasonForJs(
  CookieBoxBS.component,
  function _(jsProps) {
    return CookieBoxBS.make(jsProps.children);
  }
);

export default CookieBox;
