/* Untyped file generated by genType. */

import * as Curry from "bs-platform/lib/es6/curry.js";

import * as ReasonReact from "reason-react/src/ReasonReact.js";

import * as logoRowBS from "./logoRow.bs";

export const logoRow = ReasonReact.wrapReasonForJs(
  logoRowBS.component,
  function _(jsProps) {
    return Curry._2(logoRowBS.make, jsProps.logos, jsProps.children);
  }
);

export default logoRow;
