/* Untyped file generated by genType. */

import * as Curry from "bs-platform/lib/es6/curry.js";

import * as OrganizersBS from "./Organizers.bs";

import * as ReasonReact from "reason-react/src/ReasonReact.js";

export const Organizers = ReasonReact.wrapReasonForJs(
  OrganizersBS.component,
  function _(jsProps) {
    return Curry._2(OrganizersBS.make, jsProps.organizers, jsProps.children);
  }
);

export default Organizers;
