/* Untyped file generated by genType. */

import * as ReasonReact from "reason-react/src/ReasonReact.js";

import * as SponsorTiersBS from "./SponsorTiers.bs";

export const SponsorTiers = ReasonReact.wrapReasonForJs(
  SponsorTiersBS.component,
  function _(jsProps) {
    return SponsorTiersBS.make(jsProps.children);
  }
);

export default SponsorTiers;
