/* Untyped file generated by genType. */

import * as Curry from "bs-platform/lib/es6/curry.js";

import * as ReasonReact from "reason-react/src/ReasonReact.js";

import * as layoutBS from "./layout.bs";

export const layout = ReasonReact.wrapReasonForJs(
  layoutBS.component,
  function _(jsProps) {
    return Curry._3(
      layoutBS.make,
      [jsProps.location.pathname],
      [jsProps.file.title, jsProps.file.description, jsProps.file.keywords],
      jsProps.children
    );
  }
);

export default layout;
